"""assess_source_code - Source code assessment via AppCat JSON or app-modernization MCP.

Parses an uploaded AppCat JSON report and returns a structured assessment
focused on Managed Instance-relevant findings (registry, COM, SMTP, MSMQ, file I/O, GAC).
"""

import json
import os

from tools import server
from ps_runner import PsError, read_json_file


# AppCat rule categories relevant to Managed Instance on App Service
_MI_RELEVANT_RULES = {
    "Local.0001": "Windows Registry access — use registry adapter (ARM template / Azure Portal)",
    "Local.0003": "Local/network file I/O — use storage adapter (Azure Files / local storage / VNET)",
    "Local.0004": "Logging to local paths — use storage adapter or Azure Monitor",
    "SMTP.0001": "SMTP connections — install SMTP feature via install.ps1",
    "Security.0002": "Connection strings without config builders — use Key Vault",
    "Security.0103": "Certificate management — use Key Vault certificates",
    "Database.0003": "System.Data.SqlClient — migrate to Microsoft.Data.SqlClient for Azure SQL",
    "Scale.0001": "Static content — consider Azure CDN or Storage",
    "Logging.0103": "log4net detected — consider Azure Monitor integration",
}


@server.tool(
    name="assess_source_code",
    description=(
        "Assess source code for Azure App Service migration readiness. "
        "Accepts a path to an AppCat JSON report (generated by 'appcat analyze ... --serializer json') "
        "and returns a structured assessment with Managed Instance-relevant findings, severity classification, "
        "and recommended install.ps1 features. "
        "For source code analysis without a pre-generated report, use the app-modernization MCP tools instead."
    ),
)
async def assess_source_code(
    appcat_json_path: str,
    site_name: str = "",
) -> str:
    """Parse an AppCat report and extract Managed Instance-relevant findings.

    Args:
        appcat_json_path: Path to AppCat JSON output file.
        site_name: Optional site name to label the results.
    """
    try:
        if not os.path.isfile(appcat_json_path):
            raise PsError(
                "FILE_NOT_FOUND",
                f"AppCat JSON file not found: {appcat_json_path}. "
                "Generate it with: appcat analyze <project> --source Solution "
                "--target AppService.Windows --serializer json",
            )

        report = read_json_file(appcat_json_path)

        # AppCat JSON v1 structure:
        #   report["rules"] = dict keyed by rule ID, each value has: id, description, label, severity, effort, links
        #   report["projects"][i]["ruleInstances"] = list of incidents, each has: incidentId, ruleId, projectPath, state, location
        #   report["stats"] = summary stats
        rules_dict = {}
        incident_counts = {}
        project_info = {}

        if isinstance(report, dict):
            # Extract rules dict
            raw_rules = report.get("rules", {})
            if isinstance(raw_rules, dict):
                rules_dict = raw_rules
            elif isinstance(raw_rules, list):
                rules_dict = {r.get("id", f"rule_{i}"): r for i, r in enumerate(raw_rules)}

            # Count incidents per rule from projects
            for proj in report.get("projects", []):
                if not project_info:
                    project_info = {
                        "path": proj.get("path", ""),
                        "issues": proj.get("issues", 0),
                        "story_points": proj.get("storyPoints", 0),
                        "properties": proj.get("properties", {}),
                    }
                for ri in proj.get("ruleInstances", []):
                    rid = ri.get("ruleId", "")
                    incident_counts[rid] = incident_counts.get(rid, 0) + 1
        elif isinstance(report, list):
            # Legacy format: list of rules with embedded incidents
            rules_dict = {r.get("id", f"rule_{i}"): r for i, r in enumerate(report)}

        total_incidents = 0
        total_story_points = 0
        mandatory_issues = []
        optional_issues = []
        potential_issues = []
        install_features = set()   # OS-level: SMTP, MSMQ, Component, CrystalReports, Font
        adapter_features = set()   # Platform adapters: Registry, Storage

        for rule_id, rule in rules_dict.items():
            title = rule.get("label", rule.get("title", rule.get("Title", "")))
            description = rule.get("description", "")
            effort = rule.get("effort", rule.get("Effort", 0))
            severity = rule.get("severity", rule.get("Severity", "optional")).lower()
            # Incident count: from ruleInstances aggregation, or embedded incidents list
            incidents = rule.get("incidents", rule.get("Incidents", []))
            incident_count = incident_counts.get(rule_id, len(incidents) if isinstance(incidents, list) else 0)

            total_incidents += incident_count
            total_story_points += effort

            mi_note = _MI_RELEVANT_RULES.get(rule_id, "")

            entry = {
                "rule_id": rule_id,
                "title": title,
                "severity": severity,
                "incident_count": incident_count,
                "story_points": effort,
                "mi_relevance": mi_note,
            }

            # Map rules to features (adapter vs install script)
            if rule_id == "SMTP.0001":
                install_features.add("SMTP")
            if rule_id == "Local.0001":
                adapter_features.add("Registry")
            if rule_id in ("Local.0003", "Local.0004"):
                adapter_features.add("Storage")
            if "msmq" in title.lower() or "msmq" in description.lower():
                install_features.add("MSMQ")
            if "com " in title.lower() or "com+" in title.lower() or "interop" in title.lower():
                install_features.add("Component")
            if "crystal" in title.lower() or "crystal" in description.lower():
                install_features.add("CrystalReports")

            if severity == "mandatory":
                mandatory_issues.append(entry)
            elif severity == "optional":
                optional_issues.append(entry)
            else:
                potential_issues.append(entry)

        # Build recommendation based on detected features
        recommendations = []
        if install_features:
            recommendations.append(
                "Use generate_install_script for OS-level features: "
                + ", ".join(sorted(install_features))
            )
        if adapter_features:
            recommendations.append(
                "Use generate_adapter_arm_template for platform adapters: "
                + ", ".join(sorted(adapter_features))
                + ". Alternatively configure via Azure Portal > App Service Plan > Managed Instance settings."
            )
        if not install_features and not adapter_features:
            recommendations.append(
                "No OS-level features or adapter dependencies detected. "
                "Standard App Service deployment may suffice."
            )

        output = {
            "site_name": site_name or "unknown",
            "appcat_json_path": appcat_json_path,
            "project": project_info,
            "summary": {
                "total_rules": len(rules_dict),
                "total_incidents": total_incidents,
                "total_story_points": total_story_points,
                "mandatory_count": len(mandatory_issues),
                "optional_count": len(optional_issues),
                "potential_count": len(potential_issues),
            },
            "mandatory_issues": mandatory_issues,
            "optional_issues": optional_issues,
            "potential_issues": potential_issues,
            "install_script_features": sorted(install_features),
            "adapter_features": sorted(adapter_features),
            "recommendation": " | ".join(recommendations),
        }

        return json.dumps(output, indent=2)

    except PsError as e:
        return e.to_json()
    except Exception as e:
        return json.dumps(
            {"error": True, "error_type": "ASSESSMENT_ERROR", "message": str(e)},
            indent=2,
        )
