"""generate_install_script - Generate install.ps1 for Managed Instance on App Service.

Produces a PowerShell install script for OS-level feature enablement and
configuration on Managed Instance. This script is ONLY for scenarios requiring:
  - COM component registration / MSI installation
  - SMTP server configuration
  - MSMQ client configuration
  - Custom font installation
  - Crystal Reports runtime
  - Other Windows features that need OS-level enablement

Registry keys and local storage / file I/O dependencies should NOT be
handled via install.ps1. Use the generate_adapter_arm_template tool instead
to provision registry adapters (Key Vault-backed) and storage adapters
(Azure Files mounts, local attached storage, or custom storage over VNET).
"""

import json
import os
import textwrap

from tools import server


# Script section templates based on Managed Instance example scripts
_SCRIPT_HEADER = textwrap.dedent("""\
    #######################################################################
    # install.ps1 — Managed Instance on App Service installation script
    #
    # This script runs during app startup on the Managed Instance.
    # It installs Windows features and configures OS-level dependencies
    # required by the application.
    #
    # Generated by IIS Migration MCP Server
    #######################################################################

    $ErrorActionPreference = "Stop"
    $logFile = "D:\\\\home\\\\LogFiles\\\\install_$(Get-Date -Format 'yyyyMMdd_HHmmss').log"

    function Write-Log {
        param([string]$Message)
        $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
        $entry = "[$timestamp] $Message"
        Add-Content -Path $logFile -Value $entry
        Write-Host $entry
    }

    Write-Log "Starting Managed Instance installation script..."
""")

_SMTP_SECTION = textwrap.dedent("""\

    # ---------------------------------------------------------------
    # SMTP Server Feature
    # ---------------------------------------------------------------
    Write-Log "Installing SMTP Server feature..."
    Install-WindowsFeature -Name SMTP-Server -IncludeManagementTools

    # Configure SMTP relay (customize relay host/port as needed)
    Import-Module WebAdministration
    $smtpServer = "IIS:\\\\Smtp\\\\SmtpSvc\\\\1"
    if (Test-Path $smtpServer) {
        Write-Log "Configuring SMTP relay..."
        # Set smart host if using external relay
        # Set-ItemProperty $smtpServer -Name SmartHost -Value "smtp.example.com"
        # Set-ItemProperty $smtpServer -Name SmartHostType -Value 0
        Write-Log "SMTP configuration complete. Customize relay settings as needed."
    } else {
        Write-Log "SMTP virtual server not found — manual configuration may be required."
    }
""")

_MSMQ_SECTION = textwrap.dedent("""\

    # ---------------------------------------------------------------
    # MSMQ Feature
    # ---------------------------------------------------------------
    Write-Log "Installing MSMQ feature..."
    Install-WindowsFeature -Name MSMQ-Server -IncludeManagementTools

    # Create application queues (customize queue names as needed)
    # [System.Messaging.MessageQueue]::Create(".\\\\Private$\\\\MyQueue")
    Write-Log "MSMQ installation complete. Create application queues as needed."
""")

_CRYSTAL_REPORTS_SECTION = textwrap.dedent("""\

    # ---------------------------------------------------------------
    # Crystal Reports Runtime
    # ---------------------------------------------------------------
    Write-Log "Installing Crystal Reports runtime..."
    # Place the Crystal Reports MSI/EXE installer in the script package.
    # Download the SAP Crystal Reports runtime from SAP and include it here.
    #
    # Example: Silent install of Crystal Reports runtime
    # $crPath = Join-Path $PSScriptRoot "CRRuntime_64bit_13_0.msi"
    # if (Test-Path $crPath) {
    #     Start-Process msiexec.exe -ArgumentList "/i `"$crPath`" /q /norestart" -Wait -NoNewWindow
    #     Write-Log "Installed Crystal Reports runtime."
    # }

    Write-Log "Crystal Reports installation complete. Customize installer path as needed."
""")

_FONT_SECTION = textwrap.dedent("""\

    # ---------------------------------------------------------------
    # Custom Fonts
    # ---------------------------------------------------------------
    Write-Log "Installing custom fonts..."
    $fontsDir = "C:\\\\Windows\\\\Fonts"
    $fontFiles = Get-ChildItem -Path "$PSScriptRoot\\\\fonts" -Include *.ttf, *.otf -Recurse -ErrorAction SilentlyContinue

    foreach ($font in $fontFiles) {
        $destPath = Join-Path $fontsDir $font.Name
        if (-not (Test-Path $destPath)) {
            Copy-Item $font.FullName $destPath -Force
            # Register the font
            $regPath = "HKLM:\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Fonts"
            New-ItemProperty -Path $regPath -Name "$($font.BaseName) (TrueType)" -Value $font.Name -PropertyType String -Force
            Write-Log "Installed font: $($font.Name)"
        }
    }
    Write-Log "Font installation complete."
""")

_COMPONENT_SECTION = textwrap.dedent("""\

    # ---------------------------------------------------------------
    # COM Components / MSI Installers
    # ---------------------------------------------------------------
    Write-Log "Installing COM components..."
    # Place MSI/EXE installers in a subfolder and reference them here.
    #
    # Example: Silent MSI install
    # $msiPath = Join-Path $PSScriptRoot "components\\\\MyComponent.msi"
    # if (Test-Path $msiPath) {
    #     Start-Process msiexec.exe -ArgumentList "/i `"$msiPath`" /q /norestart" -Wait -NoNewWindow
    #     Write-Log "Installed: $msiPath"
    # }
    #
    # Example: Register COM DLL
    # $dllPath = Join-Path $PSScriptRoot "components\\\\MyComponent.dll"
    # if (Test-Path $dllPath) {
    #     regsvr32 /s $dllPath
    #     Write-Log "Registered COM: $dllPath"
    # }

    Write-Log "Component installation complete. Customize as needed."
""")

_SCRIPT_FOOTER = textwrap.dedent("""\

    # ---------------------------------------------------------------
    # Finalize
    # ---------------------------------------------------------------
    Write-Log "Managed Instance installation script completed successfully."
""")

_FEATURE_SECTIONS = {
    "SMTP": _SMTP_SECTION,
    "MSMQ": _MSMQ_SECTION,
    "Font": _FONT_SECTION,
    "Component": _COMPONENT_SECTION,
    "CrystalReports": _CRYSTAL_REPORTS_SECTION,
}


@server.tool(
    name="generate_install_script",
    description=(
        "Generate an install.ps1 PowerShell script for Managed Instance on App Service. "
        "The script installs OS-level Windows features and configures dependencies "
        "that require feature enablement: COM/MSI installation, SMTP server, MSMQ client, "
        "custom fonts, Crystal Reports runtime, and similar OS-level components.\n\n"
        "IMPORTANT: Registry keys and local storage / file I/O dependencies should NOT "
        "be handled via install.ps1. Use the generate_adapter_arm_template tool instead "
        "to provision registry adapters (Key Vault-backed) and storage adapters "
        "(Azure Files, local storage, custom storage over VNET)."
    ),
)
async def generate_install_script(
    site_name: str,
    features: str = "",
    output_path: str = "",
    config_assessment_json: str = "",
    source_assessment_json: str = "",
) -> str:
    """Generate install.ps1 for Managed Instance on App Service.

    Args:
        site_name: The site name (used for labeling and default output path).
        features: Comma-separated features to include: SMTP, MSMQ, Font, Component, CrystalReports.
                  If empty, features are auto-detected from assessment results.
                  Note: Registry and Storage features are handled by generate_adapter_arm_template.
        output_path: Custom path for the generated script. Defaults to temp directory.
        config_assessment_json: JSON string of config assessment for auto-detection.
        source_assessment_json: JSON string of source assessment for auto-detection.
    """
    detected_features = set()

    # Manual features override
    if features:
        for f in features.split(","):
            f = f.strip()
            if f in _FEATURE_SECTIONS:
                detected_features.add(f)

    # Auto-detect from config assessment (OS-level features only)
    if not detected_features and config_assessment_json:
        try:
            config = json.loads(config_assessment_json)
            for check in config.get("failed_checks", []):
                check_id = check.get("check_id", "") if isinstance(check, dict) else str(check)
                # Registry is handled by adapter ARM template, NOT install script
                if "GAC" in check_id or "COM" in check_id:
                    detected_features.add("Component")
                if "MSMQ" in check_id:
                    detected_features.add("MSMQ")
        except json.JSONDecodeError:
            pass

    # Auto-detect from source assessment
    if source_assessment_json:
        try:
            source = json.loads(source_assessment_json)
            for feature in source.get("install_script_features", []):
                if feature in _FEATURE_SECTIONS:
                    detected_features.add(feature)
        except json.JSONDecodeError:
            pass

    # If no OS-level features detected, return guidance instead of empty script
    if not detected_features:
        return json.dumps({
            "install_script_path": "",
            "site_name": site_name,
            "features_included": [],
            "note": (
                "No OS-level features requiring install.ps1 were detected. "
                "If the site has Registry or Storage dependencies, use the "
                "generate_adapter_arm_template tool to provision adapters instead."
            ),
        }, indent=2)

    # Build script
    script_parts = [_SCRIPT_HEADER]
    for feature in sorted(detected_features):
        if feature in _FEATURE_SECTIONS:
            script_parts.append(_FEATURE_SECTIONS[feature])
    script_parts.append(_SCRIPT_FOOTER)
    script_content = "\n".join(script_parts)

    # Write to file
    if not output_path:
        import tempfile
        output_dir = os.path.join(tempfile.gettempdir(), "iis-migration", site_name)
        os.makedirs(output_dir, exist_ok=True)
        output_path = os.path.join(output_dir, "install.ps1")

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(script_content)

    output = {
        "install_script_path": output_path,
        "site_name": site_name,
        "features_included": sorted(detected_features),
        "script_preview": script_content[:2000] + ("..." if len(script_content) > 2000 else ""),
        "note": (
            "Review the generated script and customize placeholder values "
            "(registry keys, queue names, relay hosts, installer paths). "
            "The script will run during app startup on the Managed Instance."
        ),
    }

    return json.dumps(output, indent=2)
